### ISSUE TITLE
Можно упростить

### ISSUE THREAD

**Issue by Aikava** [postneprost/getMoney#1]
https://github.com/postneprost/getMoney/blob/c1c7c7700a2cf7eaa5e9c5288a93925de0b35ed6/getMoney.js#L47

Думаю что вариант с Boolean(countMoney[banknote]) будет рабочий. Любой ключ который не существует в объекте, при попытке получить его значение вернет undefined.
[Глава Objects and properties](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Working_with_Objects)

**Comment by postneprost** [comment]
done
